/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_thoughtcrime_redphone_audio_CallAudioManager2 */

#ifndef _Included_org_thoughtcrime_redphone_audio_CallAudioManager2
#define _Included_org_thoughtcrime_redphone_audio_CallAudioManager2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_thoughtcrime_redphone_audio_CallAudioManager2
 * Method:    start
 * Signature: (IIIILjava/lang/String;I[B)V
 */
JNIEXPORT void JNICALL Java_org_thoughtcrime_redphone_audio_CallAudioManager2_start
  (JNIEnv *, jobject, jint, jint, jint, jint, jstring, jint, jbyteArray);

JNIEXPORT void JNICALL Java_org_thoughtcrime_redphone_audio_CallAudioManager2_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
