/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_thoughtcrime_redphone_audio_CallAudioManager2 */

#ifndef _Included_org_thoughtcrime_redphone_audio_CallAudioManager2
#define _Included_org_thoughtcrime_redphone_audio_CallAudioManager2
#ifdef __cplusplus

#include "SrtpStream.h"

class CallAudioManager {

private:
//  int                srtp_initialized;
  SLObjectItf        engineObject;
  SLEngineItf        engineEngine;
  AudioCodec         audioCodec;
  RtpAudioSender     audioSender;
  RtpAudioReceiver   audioReceiver;
  WebRtcJitterBuffer webRtcJitterBuffer;
  MicrophoneReader   microphoneReader;
  AudioPlayer        audioPlayer;

public:
  CallAudioManager(int androidSdkVersion, int socketFd, struct sockaddr_in *sockAddr,
                   SrtpStreamParameters &senderParameters, SrtpStreamParameters &receiverParameters);
  ~CallAudioManager();
  int run();

//static int startAudio(int androidSdkVersion, int sampleRate, int bufferFrames,
//                      int socketFd, const char* serverIp, int serverPort,
//                      char* masterKey)


};

extern "C" {
#endif
/*
 * Class:     org_thoughtcrime_redphone_audio_CallAudioManager2
 * Method:    start
 * Signature: (IIIILjava/lang/String;I[B)V
 */
JNIEXPORT void JNICALL Java_org_thoughtcrime_redphone_audio_CallAudioManager2_start
  (JNIEnv *, jobject, jint, jint, jint, jint, jstring, jint,
   jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

JNIEXPORT void JNICALL Java_org_thoughtcrime_redphone_audio_CallAudioManager2_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
