/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_thoughtcrime_redphone_audio_CallAudioManager2 */

#ifndef _Included_org_thoughtcrime_redphone_audio_CallAudioManager2
#define _Included_org_thoughtcrime_redphone_audio_CallAudioManager2
#ifdef __cplusplus

#include "SrtpStream.h"
#include "Clock.h"

class CallAudioManager {

private:
  volatile int       running;
  SLObjectItf        engineObject;
  SLEngineItf        engineEngine;
  AudioCodec         audioCodec;
  RtpAudioSender     audioSender;
  RtpAudioReceiver   audioReceiver;
  WebRtcJitterBuffer webRtcJitterBuffer;
  Clock              clock;
  MicrophoneReader   microphoneReader;
  AudioPlayer        audioPlayer;
  struct sockaddr_in *sockAddr;

public:
  CallAudioManager(int androidSdkVersion, int socketFd, struct sockaddr_in *sockAddr,
                   SrtpStreamParameters *senderParameters, SrtpStreamParameters *receiverParameters);
  ~CallAudioManager();

  int start();
  void stop();

  void setMute(int muteEnabled);

};

extern "C" {
#endif
/*
 * Class:     org_thoughtcrime_redphone_audio_CallAudioManager2
 * Method:    start
 * Signature: (IIIILjava/lang/String;I[B)V
 */
JNIEXPORT jlong JNICALL Java_org_thoughtcrime_redphone_audio_CallAudioManager2_create
  (JNIEnv *, jobject, jint, jint, jstring, jint,
   jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

JNIEXPORT void JNICALL Java_org_thoughtcrime_redphone_audio_CallAudioManager2_start
  (JNIEnv *, jobject, jlong);

JNIEXPORT void JNICALL Java_org_thoughtcrime_redphone_audio_CallAudioManager2_stop
  (JNIEnv *, jobject, jlong);

JNIEXPORT void JNICALL Java_org_thoughtcrime_redphone_audio_CallAudioManager2_setMute
  (JNIEnv *, jobject, jlong, jboolean);

JNIEXPORT void JNICALL Java_org_thoughtcrime_redphone_audio_CallAudioManager2_dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
